wetware/ww

pkg/cap/cluster/anchor_test.go
pkg/cap/pubsub/client.go

I discovered this bug while working on a system that uses ww pubsub.  This system had a deadlock that prevented it from reading additional items from an open subscription.  As a result, the client-side subscription's internal buffer filled up fairly quickly, which would subsequently cause the capnp `rpc.Conn` to time out.
The fix is to make subscription handler capabilities non-blocking.  This means we now drop messages if the subscriber is not consuming them fast enough (which is what libp2p does anyway).

Fix rpc.Conn disconnect when subscription buffer is full

---

api/pubsub.capnp
go.mod
internal/api/pubsub/pubsub.capnp.go
pkg/cap/pubsub/client.go
pkg/cap/pubsub/server.go
pkg/cap/pubsub/server_test.go
pkg/cap/pubsub/subscription_test.go
pkg/client/client.go
pkg/client/pubsub.go
pkg/client/pubsub_test.go

After going back and forth, I think it was a mistake to provide pubsub capabilities in the form of an interface.
There are a couple of things I failed to consider:
1. We need a way of passing capabilities as arguments, which means we need to be able to access the underlying `*capnp.Client`.
2. We _could_ do something like `client.Topic.Client()`, but I think our API will be easier to consume if we adhere to the go-capnproto standard of `type Foo struct{ Client: *capnp.Client }`.
3. Capabilities are exactly equivalent to interfaces, functionally speaking.  Although it's syntactically a bit more tedious, capabilities are easily mocked by writing custom cap servers, and deriving clients (as demonstrated in the present PR).

Export capability clients for pubsub.

---

go.mod
go.sum
internal/cmd/client/discover.go

- CASM uses master tip, which fixes CIDR /32 iterator
- `ww client discover` command removes duplicates for the `discover` and `ns` arguments

Updated CASM + removed duplicated args

---

go.mod
go.sum
internal/api/anchor/anchor.capnp.go
internal/api/channel/channel.capnp.go
internal/api/cluster/cluster.capnp.go
internal/api/iostream/iostream.capnp.go
internal/api/proc/proc.capnp.go
internal/api/pubsub/pubsub.capnp.go
pkg/client/dialer_test.go
pkg/client/pubsub.go
pkg/vat/cap/anchor/anchor.go
pkg/vat/cap/cluster/host.go
pkg/vat/cap/cluster/view.go
pkg/vat/cap/process/unix/process.go
pkg/vat/cap/process/unix/unix.go
pkg/vat/cap/pubsub/server.go
pkg/vat/future.go
pkg/vat/vat.go

This PR upgrades the version of go-capnp to `3.0.0-alpha.4`, which includes minor bugfixes and minor breaking API changes.  The most notable API change is documented [here](https://github.com/capnproto/go-capnproto2/pull/260).
The diff is quite noisy, but reduces to exactly two things:
1. Update `go.mod` and `go.sum`
2. Refactor `*capnp.Client` into concrete `capnp.Client`.

Upgrade to capnp v3.0.0-alpha.4

---

internal/runtime/network.go
pkg/vat/cap/pubsub/pubsub_bench_test.go

This PR improves the performance of the pubsub system, replacing RSA signing with Ed25519 signing #43 . Benchmarks have been included to compare the different signings, including no signing at all.

Ed25519 identity for libp2p host, instead of RSA + bechmarks for pubsub

---

api/pubsub.capnp
internal/api/pubsub/pubsub.capnp.go
pkg/client/pubsub.go
pkg/vat/cap/pubsub/client.go
pkg/vat/cap/pubsub/server.go

This PR intends to improve pubsub capability performance by:
- Making capnp RPC calls parallel with call.Ack()
- Making subscription buffers configurable in multiple places: (1) libp2p subscription buffer, (2) capnp policy and (3) capnp subscription flowlimiter. All of them are set to the same size of the user buffer size.

Publish call made parallel using ACK + configurable subscription buffer

---

internal/cmd/client/discover.go
internal/cmd/client/runtime.go
internal/runtime/network.go

Current discovery takes too much time to scan a CIDR of /18, I increased the rate limiter for finding peers in the order of seconds, not minutes

Increased discovery rate limiter

---

.github/workflows/go.yml

v2 is outputting a deprecation notice, so upgrade to v3.

Upgrade GitHub Actions to v3.

---

go.mod
go.sum

This updates [wazero](https://wazero.io/) to [1.0.0-pre.3](https://github.com/tetratelabs/wazero/releases/tag/v1.0.0-pre.3). This is the last release that will build with Go 1.17.
Notably, this improves performance and changes host function syntax.

deps: updates wazero to 1.0.0-pre.3

---

pkg/client/dialer.go

https://github.com/wetware/casm/pull/52 fixes issue where unlimited discovery streams were unbuffered, causing all but the first peer to be dropped during initial connection attempt.  As such, the workaround of setting a high limit is no longer needed.
Note that CASM now uses a static buffer with `cap=16`, so it is expected that slow consumers may miss all but the first 17 peers (first peer is immediately consumed from the channel, the buffer fills to cap=16).  In practice, this is not a problem since 16 peers is very generous for an initial bootstrap.

Remove discovery.Limit from client.Dialer.join

---

internal/cmd/cluster/cluster.go

Also noticed that start.go and debug.go have the same exact teardown() as cluster.go

fixed code from meeting

---

go.mod
go.sum
pkg/csp/chan.go
pkg/csp/stream.go
pkg/csp/stream_test.go

This PR adds a `NewStream` method to `csp.Chan` and its derivatives.  This adds support for [flow-controlled streams](https://capnproto.org/news/2020-04-23-capnproto-0.8.html) to channels, which should greatly improve performance for large volumes of concurrent sends.
@mikelsr This is especially relevant to your work on processes, since `iostream` is implemented using `csp.Chan` under the hood.  Use of `csp.SendStream` in `iostream` will be submitted in a separate PR.
(cc @aratz-lasa @evan-schott for general awareness.  Code-review & feedback is most welcome.)

Add streaming send capability to csp.Chan

---

pkg/runtime/runtime.go
pkg/server/config.go
pkg/server/server.go

We previously factored `*pubsub.PubSub` out of CASM to **greatly** simplify the lifecycle logic of the CASM cluster model.  The flip side of this is that we find ourselves holding two objects on the Wetware side that really ought to be merged into one object:  `server.Router` (wetware) and `cluster.Router` (casm).
This PR introduces the `Cluster` interface, which abstracts the binding of these two types.  Along the way, it cleans up a few symbol names and does some minor refactoring of configuration logic in `Joiner` (e.g. avoiding duplicate params, and passing stateful dependencies as function arguments).
_____
cc @evan-schott and @mikelsr because this is a very simple change to the code responsible for starting a server when you run `ww start`.  I thought it might be illuminating in …

Refactor server code

---

go.mod
go.sum
pkg/csp/chan.go

Follow up of https://github.com/wetware/casm/pull/71.  Replaces use of `casm.FuturePtr` in `csp` package with `csp.Future`, which is actually correct.
This PR is in draft until https://github.com/wetware/casm/pull/71 is merged, and the local version of CASM can be upgraded.

Replace casm.Future with csp.Future.

---

pkg/csp/chan.go

Allows callers to send more value types through a channel.  Existing `csp.Value` implementations are made generic.

Add generic CSP value types

---

pkg/csp/chan.go

It makes no sense to block while waiting for a capability since we can pipeline calls.  This PR returns a promised capability from `csp.Future.Client()` and removes `AwaitClient()`.

Return promised capability from csp.Future

---

api/pubsub.capnp
internal/api/pubsub/pubsub.capnp.go
pkg/pubsub/subscription.go
pkg/pubsub/topic.go

This is a prerequisite for the WIP channel implementation.  The API no longer supports streaming sends to channels (it turns out the semantics were broken), so pubsub subscribers now use a specialized `Consumer` capability instead.

Don't use channel.Sender in pubsub.

---

internal/cmd/start/start.go

Fixes #96.
I went through several iterations of this in which I tried to make clever use of `net.Interfaces()`, but ultimately gave up and went with a static `switch` statement.  This should be correct most of the time, and we can add cases to the switch statement as needed.  I'm not sure how many of these platforms we'll end up supporting, anyway.
I'm open to ideas.

Infer loopback multicast address from runtime.GOOS.

---

go.mod
go.sum
pkg/process/executor_test.go
pkg/process/process.go

This updates [wazero](https://wazero.io/) to [1.0.0](https://github.com/tetratelabs/wazero/releases/tag/v1.0.0) which begins our compatibility promise.
On behalf of everyone in the community, I want to thank you for trying wazero before we became stable. We will not raise unsolicited pull requests anymore. That said, if any update gives you problems, please feel free to contact [us](https://wazero.io/community/) on slack or via a GitHub issue.
Finally, if you would like to share your work, feel free to update our [users page](https://github.com/tetratelabs/wazero/blob/main/site/content/community/users.md)!

deps: updates wazero to 1.0.1

---

pkg/runtime/option.go
pkg/runtime/runtime.go
pkg/runtime/wasm.go

Creates a `wazero.RuntimeConfig` in Fx (`pkg/runtime`) that enables two features:
- Shared compilaton cache across all `wazero.Runtime` instances
- `WithCloseOnContextDone`
```go
// WithCloseOnContextDone ensures the executions of functions to be closed under one of the following circumstances:
//
// 	- context.Context passed to the Call method of api.Function is canceled during execution. (i.e. ctx by context.WithCancel)
// 	- context.Context passed to the Call method of api.Function reaches timeout during execution. (i.e. ctx by context.WithTimeout or context.WithDeadline)
// 	- Close or CloseWithExitCode of api.Module is explicitly called during execution.
//
// This is especially useful when one wants to run untrusted Wasm binaries since otherwise, any invocation of
// api.Function …
```

Generate default wazero.RuntimeConfig from Fx.

---

api/process.capnp
internal/api/process/process.capnp.go
pkg/process/process.go

Small cleanup following #100.  Removes deprecated `ExitError` schema.

Simplify exit error schema.

---

cmd/ww/main.go
internal/cmd/run/run.go

This PR provides a command for executing WASM binaries locally.  It is part of the workstream to break #111 into smaller chunks.
Commented code will be uncommented in a follow-up commit that adds piecemeal support for the ww host module.
If you want to test this, try compiling the following with `tinygo -o main.wasm -target=wasi main.go`, and running it with `ww run main.wasm`.
```go
package main
import "fmt"
// main.go
func main() {
fmt.Println("hello, wetware!")
}
```

Add ww run command.  

---

pkg/csp/chan.go

Note that I haven't tested this yet.  @evan-schott If you're feeling lucky, feel free to merge.  Worst-case-scenario it doesn't work, in which case, just open an issue and we'll get it fixed.
To convert the pointer back into a client:  `ptr.Interface().Client()`.

`Add csp.Client function to send capabilities over a channel.

---

pkg/runtime/routing.go

While helping Evan with his demo, I noticed that DHT routing is not enabled for Wetware hosts.  This is because of a bug in `pkg/runtime`.  The `fx.Decorator` that wraps `host.Host` with a `routedhost.Host` was not being called because we don't actually declare a constructor for `host.Host`.  This has been fixed by decorating `casm.Vat` instead.

Bugfix:  ensure Vat.Host is decorated with DHT routing.

---

go.mod
go.sum
internal/cmd/run/run.go
pkg/csp/executor.go
pkg/csp/proc/proc.go
pkg/server/config.go

Adds `ww` host module implementation and binds it to the WASM runtime.  A follow-up PR will introduce the guest library, which receives the bootstrap capability provided by the host module.

Add host module for calling wetware capabilities from proc.

---

pkg/csp/chan.go

Fixes non-blocking loop issue encountered by @evan-schott.
Also adds `.Await()` and `.Err()` methods.

Block when resolving csp.Future.Client()

---

pkg/server/server.go

This pull request adds the pubsub capability to the embedded WW server in order to enhance its functionality.
The main changes in this PR include:
1. The addition of the `PubSubProvider` field to the `Node` struct, which represents a pubsub provider for the server.
2. Modification of the `Join` method in the `Node` struct to initialize the pubsub provider using the `j.pubsub` function, passing the appropriate parameters.
3. In the `Join` method, the `PubSubProvider` field is assigned the value returned by the `j.pubsub` function.
4. In the `vat.Export` function call within the `Join` method, the `PubSubProvider` is included as part of the `host.Server` struct.
These changes enable the embedded WW server to support pubsub functionality, allowing for efficient communication and message …

Add pubsub capability to embedded ww server
